### ISSUE TITLE
Avatar animate is delay 3s 

### ISSUE THREAD

**Issue by superkudo** [SeedV/SeedUnityVRKit#34]
In SeedAvatarStuido with SeedArkitUnity 0.2.0  avatar animate delay 3s , the fps is about 20

**Comment by henryouly** [comment]
I have some ideas what may affect performance in 0.2.0. Let me try to make some fixes and please help me to verify.

**Comment by superkudo** [comment]
Get it

**Comment by henryouly** [comment]
Discussed that the attempt fix doesn't solve the issue. This issue happened before 0.2.0-alpha drop (which explains why the fix is not sufficient), and the reason is can be anything from computer bottleneck, memory leak, upstream bugs, etc.

**Comment by henryouly** [comment]
Added some logs in PR #36 to try to narrow down the problem to a certain component.

**Comment by superkudo** [comment]
0.3.0-alpha the delay is solved in my mac

**Comment by henryouly** [comment]
Hmm, I didn't expect the animation delay can be improved by this version.

Maybe the delay was introduced in https://github.com/SeedV/SeedUnityVRKit/pull/24. https://github.com/SeedV/SeedUnityVRKit/pull/32 reverts most of that change and switches to a new implementation.

Anyway, this is great. I'll close the issue now.
