### ISSUE TITLE
Eyes animate is not sensitive

### ISSUE THREAD

**Issue by superkudo** [SeedV/SeedUnityVRKit#35]

**Comment by henryouly** [comment]
Can you explain what it means by eyes animate not sensitive?

- No blinking animation (eyes just kept open or close)
- Too sensitive (the model created the blinking animation when it shouldn’t, false positive)

There’s an eye open threshold currently set to 0.33. I guess that requires some refinement for optimal result.

**Comment by superkudo** [comment]
I send test video in email, I guess it also effect by animate delay issue

**Comment by henryouly** [comment]
Discussed offline - this is because of having local changes. Not a valid issue.
