### ISSUE TITLE
about control model

### ISSUE THREAD

**Issue by JokerWooByAson** [SeedV/SeedUnityVRKit#52]
Why is it that when I import a model and start video capture, both hands and feet of the model are raised to the head
The initialization is normal, but it is abnormal after the update is enabled

**Comment by JokerWooByAson** [comment]
i think ... this , in Update() --> jointPoint.SetRotation(...) ?   and i try modify here ... 
if you can tell me how to modify,that would be better

**Comment by henryouly** [comment]
I'm not able to see what you described using `WebCam` as `Input Mode` in `InputController` gameobject.

Do you mind to specify the scene you used? (There are two scenes - `SampleScene` is the one for a full body recognition that works best if you have a 2 meter distance from the camera to capture whole body movement, and `VTuber` is one for upper body and face, which works best to stand closer to the camera.)

Also, if you can capture a video, can you change `Input Mode` to `Video` to see if that's the same issue in video mode? If that's the case, you can share the video to me privately to my email address `henryouly@gmail.com` and I can see if I can repro using the video.
